name: tutorials

# CINTENT >> MANUAL_TRIGGER
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - docs/tutorials/**
#   pull_request:
#     branches:
#       - main
#     paths:
#       - docs/tutorials/**
on: [repository_dispatch, workflow_dispatch]

defaults:
  run:
    shell: bash
jobs:
  notebooks:
    name: notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5.0.0

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
      
      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      # CINTENT >> REMOVE_CACHE
      # - name: Cache dependencies
      #   uses: actions/cache@v4.2.4
      #   id: cache
      #   with:
      #     path: ${{ env.pythonLocation }}
      #     key: ${{ runner.os }}-${{ runner.arch }}-Python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements/required.txt', 'requirements/docs.txt', 'requirements/tests.txt') }}-tutorials
      
      - name: Install pip dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements/required.txt -r requirements/docs.txt -r requirements/tests.txt planetary_computer pystac tensorboard h5py scikit-learn .
          pip cache purge
          
      - name: List pip dependencies
        run: pip list

      - name: Run notebook checks
        run: pytest --nbmake --durations=10 docs/tutorials

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
